name: googleapis_auth
version: 0.1.0
author: Dart Team
description: Library to get access credentials from Google using oauth2.
environment:
  sdk: '>=1.3.0 <2.0.0'
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.11.1 <0.12.0'
dev_dependencies:
  unittest: any
